version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=django
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
